name: Sync fork

on:
  schedule:
    # Every Friday, every 15 minutes between 9-12
    - cron: '*/15 9-12 * * 5'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: Simpsonpt
          repo: AppSecEzine
          base: master
          head: master
          ignore_fail: true
          retries: 1